language: java
jdk:
  - openjdk11

# master 브랜치에 push될 때만 수행
branches:
  only:
    - master

before_install:
  - chmod +x gradlew

# deploy 명령어가 실행되기 전에 수행되며 CodeDeploy는 Jar 파일을 인식하지 못하므로 Jar+기타 설정 파일들을 모아 압축한다.
before_deploy:
  - zip -r L.E.Assemble-back * # 현재 위치의 모든 파일을 압축.
  - mkdir -p deploy
  - mv L.E.Assemble-back.zip deploy/L.E.Assemble-back.zip

# S3로 파일 업로드 혹은 CodeDeploy로 배포 등 외부 서비스와 연동될 행위들을 선언한다.
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된  값
    bucket: leassemble-bucket	 # S3 버킷
    region: us-east-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deploy: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된  값
    bucket: leassemble-bucket # S3 버킷
    key: L.E.Assemble-back.zip # 빌드 파일을 압축해서 전달
    bundle_type: zip
    application: leassemble # 웹 콘솔에서 등록한 CodeDeploy 애플리케이션
    deployment_group: leassemble-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: us-east-2
    wait-until-deployed: true

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - lsoonnoon@gmail.com
